* The IRClogs Scheme system

IRClogs is a software package written in [[http://en.wikipedia.org/wiki/Scheme_(programming_language)][Scheme]], presenting a web
interface to a collection of IRC logs. 

** Features

- Serve logs from multiple channels, organized by "tags", which
  normally correspond to IRC networks

- Overview pages for all channels logged, all channels logged with a
  given tag, and a single channel. These overview pages are
  navigatable by date.

- The text log files rendered as HTML tables, with messages
  color-coded indicating the nick sending the message.

- Search a channel for messages

** Planned features

- Toggling of channel events (joins, quits, etc.) via JavaScript or a
  query option (JavaScript part already implemented)

- Improve search:

  - Interrupt search after consuming a configured amount of time, with
    option to resume
  - Links directly to log at the times of the hits
  - Specify amount of context around a message to show
  - Allow explicitly specifying base date
  - Highlight matches
  - Allow toggling of events on search result pages as well
  - Carry search string to the result page
  - Feedback on the interpretation of the query: What base date and
    day count was used, what matchers where constructed

- Allow a single instance to offer several (possibly overlapping) sets
  of channels on different ports. This is useful if you want to run an
  IRClogs instance serving your logs, and want to have a "public
  view", presented to the interweb, and a "private view" that you
  restrict access to via HTTP authentication, IP address or some other
  mechanism.

** Instances

Currently, there's an experimental instance of IRClogs running at
[[http://rottyforge.yi.org/irclogs/]], serving a few select channels on
the GNOME and freenode networks.

** Documentation

*** Searching

A search always has a "base date", and a number of days it reaches
backwards; both have default values:

- The "base date" defaults to the current date, if no ~date~ query
  option is given in the URL, which is the case when you initially
  enter a channel activity overview page. If you use the navigation
  links or the "pin" links presented for each day to navigate to
  another day, that changes the base date to the corresponding day.

- The number of days searched by default is 14, this option can be
  changed in the configuration file.

The phrase (interpreted as character string) entered into the search
field is parsed into a list of "search parameters" according to the
following rules:

- As long as possible, an item is consumed from the string by using
  the Scheme procedure for reading a datum ([[http://www.schemers.org/Documents/Standards/R5RS/HTML/r5rs-Z-H-9.html#%_idx_612][R5RS read]], [[http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html#node_idx_708][R6RS
  get-datum]]). If parsing fails at some point, the entire remainder of
  the string is consumed a single item. This step results in a list of
  Scheme datums. For example:

  - ~foo bar "hello world" 42~ results in the list ~(foo bar "hello
    world" 42)~.

  - ~(date "2008-10-26") (days 42) foo)~ results in the list ~((date
    "2008-10-26") (days 42) "foo) 123")~.

**** TODO: Finish this section

** Support

Currently, there's no documentation on how to set up an IRClogs
instance, so if you have questions about that or anything else, want
to help out, or think you have found a bug, or want to provide any
other kind of feedback, after having a look at the [[http://rottyforge.yi.org/cgi-bin/darcsweb.cgi?r=irclogs;a=headblob;f=/README][README]], and taking
a look at the [[http://rottyforge.yi.org/cgi-bin/darcsweb.cgi?r=irclogs;a=summary][Source]] (if you're brave ;-)) I usually hang out on
[[http://rottyforge.yi.org/irclogs/freenode/%23scheme/][irc://freenode/#scheme]] as ~rotty~ -- just send me a ping, but don't
hold your breadth.
